/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortGeoLocation = IDL.Record({
  'latitude' : IDL.Text,
  'name' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'longitude' : IDL.Text,
});
export const Port = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'geoPoints' : IDL.Vec(PortGeoLocation),
  'coordinates' : IDL.Text,
  'warehouses' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addGeoPoint' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPort' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(PortGeoLocation),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addPortOfTemaData' : IDL.Func([], [], []),
  'addWarehouse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'cleanUpBerthingData' : IDL.Func([], [], []),
  'getAllPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
  'getPortById' : IDL.Func([IDL.Nat], [IDL.Opt(Port)], ['query']),
  'getPortOfTemaData' : IDL.Func([], [Port], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortGeoLocation = IDL.Record({
    'latitude' : IDL.Text,
    'name' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'longitude' : IDL.Text,
  });
  const Port = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'geoPoints' : IDL.Vec(PortGeoLocation),
    'coordinates' : IDL.Text,
    'warehouses' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addGeoPoint' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPort' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(PortGeoLocation),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addPortOfTemaData' : IDL.Func([], [], []),
    'addWarehouse' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'cleanUpBerthingData' : IDL.Func([], [], []),
    'getAllPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
    'getPortById' : IDL.Func([IDL.Nat], [IDL.Opt(Port)], ['query']),
    'getPortOfTemaData' : IDL.Func([], [Port], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };