/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Port {
  'id' : bigint,
  'region' : string,
  'country' : string,
  'name' : string,
  'size' : string,
  'geoPoints' : Array<PortGeoLocation>,
  'coordinates' : string,
  'warehouses' : Array<string>,
}
export interface PortGeoLocation {
  'latitude' : string,
  'name' : string,
  'type' : string,
  'description' : string,
  'longitude' : string,
}
export interface Tugboat {
  'id' : bigint,
  'year_built' : bigint,
  'engine_power_hp' : bigint,
  'length_m' : bigint,
  'flag' : string,
  'name' : string,
  'port' : string,
  'bollard_pull_ton' : bigint,
}
export interface _SERVICE {
  'addGeoPoint' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'addPort' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<PortGeoLocation>,
      Array<string>,
    ],
    bigint
  >,
  'addPortOfTemaData' : ActorMethod<[], undefined>,
  'addTugboatsForTemaPort' : ActorMethod<[], undefined>,
  'addWarehouse' : ActorMethod<[bigint, string], undefined>,
  'cleanUpBerthingData' : ActorMethod<[], undefined>,
  'getAllPorts' : ActorMethod<[], Array<Port>>,
  'getAllTugboats' : ActorMethod<[], Array<Tugboat>>,
  'getPortById' : ActorMethod<[bigint], [] | [Port]>,
  'getPortOfTemaData' : ActorMethod<[], Port>,
  'getTugboatById' : ActorMethod<[bigint], [] | [Tugboat]>,
  'getTugboatsByPort' : ActorMethod<[string], Array<Tugboat>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];