/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Port {
    id: bigint;
    region: string;
    country: string;
    name: string;
    size: string;
    geoPoints: Array<PortGeoLocation>;
    coordinates: string;
    warehouses: Array<string>;
}
export interface PortGeoLocation {
    latitude: string;
    name: string;
    type: string;
    description: string;
    longitude: string;
}
export interface Tugboat {
    id: bigint;
    year_built: bigint;
    engine_power_hp: bigint;
    length_m: bigint;
    flag: string;
    name: string;
    port: string;
    bollard_pull_ton: bigint;
}
export interface backendInterface {
    addGeoPoint(portId: bigint, name: string, description: string, type: string, latitude: string, longitude: string): Promise<void>;
    addPort(name: string, country: string, region: string, size: string, coordinates: string, geoPoints: Array<PortGeoLocation>, warehouses: Array<string>): Promise<bigint>;
    addPortOfTemaData(): Promise<void>;
    addTugboatsForTemaPort(): Promise<void>;
    addWarehouse(portId: bigint, warehouseName: string): Promise<void>;
    cleanUpBerthingData(): Promise<void>;
    getAllPorts(): Promise<Array<Port>>;
    getAllTugboats(): Promise<Array<Tugboat>>;
    getPortById(id: bigint): Promise<Port | null>;
    getPortOfTemaData(): Promise<Port>;
    getTugboatById(id: bigint): Promise<Tugboat | null>;
    getTugboatsByPort(portName: string): Promise<Array<Tugboat>>;
}
import type { Port as _Port, Tugboat as _Tugboat } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGeoPoint(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGeoPoint(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGeoPoint(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addPort(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<PortGeoLocation>, arg6: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPort(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPort(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addPortOfTemaData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPortOfTemaData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPortOfTemaData();
            return result;
        }
    }
    async addTugboatsForTemaPort(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTugboatsForTemaPort();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTugboatsForTemaPort();
            return result;
        }
    }
    async addWarehouse(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWarehouse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWarehouse(arg0, arg1);
            return result;
        }
    }
    async cleanUpBerthingData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanUpBerthingData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanUpBerthingData();
            return result;
        }
    }
    async getAllPorts(): Promise<Array<Port>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPorts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPorts();
            return result;
        }
    }
    async getAllTugboats(): Promise<Array<Tugboat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTugboats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTugboats();
            return result;
        }
    }
    async getPortById(arg0: bigint): Promise<Port | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortOfTemaData(): Promise<Port> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortOfTemaData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortOfTemaData();
            return result;
        }
    }
    async getTugboatById(arg0: bigint): Promise<Tugboat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTugboatById(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTugboatById(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTugboatsByPort(arg0: string): Promise<Array<Tugboat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTugboatsByPort(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTugboatsByPort(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Port]): Port | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tugboat]): Tugboat | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
